#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BallsOfSteel.Resource", IsApplication=true)]

namespace BallsOfSteel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SiliconStudio.Xenko.Resource.Id.EditTextLayout = global::BallsOfSteel.Resource.Id.EditTextLayout;
			global::SiliconStudio.Xenko.Resource.Id.GameMainLayout = global::BallsOfSteel.Resource.Id.GameMainLayout;
			global::SiliconStudio.Xenko.Resource.Id.GameViewLayout = global::BallsOfSteel.Resource.Id.GameViewLayout;
			global::SiliconStudio.Xenko.Resource.Layout.Game = global::BallsOfSteel.Resource.Layout.Game;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int EditTextLayout = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int GameMainLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int GameViewLayout = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
